stages:
  - build

build and public:
  stage: build
  script:
    - export TMPDIR=/tmp/.private/${USER}; export TMP=${TMPDIR}

    - git remote | grep -q gitlab || git remote add gitlab git@gitlab.eterfund.ru:/pv/prunner

    - |
        echo "BUILD NEW VERSION: $CI_PROJECT_NAME" >> changes.txt
        /usr/bin/rpmlog -t | tail +2 >> changes.txt

    - /usr/bin/rpmlog -q -r -l
    - korinf -f prunner.spec x86_64/ALTLinux/p8 /var/ftp/pvt/Etersoft/RX@Etersoft/unstable
    - korinf -f prunner.spec x86_64/ALTLinux/Sisyphus /var/ftp/pvt/Etersoft/RX@Etersoft/unstable
    - korinf -f prunner.spec x86_64/ALTLinux/p7 /var/ftp/pvt/Etersoft/RX@Etersoft/unstable
    - korinf -f prunner.spec x86_64/ALTLinux/c7 /var/ftp/pvt/Etersoft/RX@Etersoft/c7
    - git push -f --tags gitlab HEAD:master
    - rx_bot_pub_file.py changes.txt || echo "ignore public bot error.."

  after_script:
    - mkdir -p RPM/log; cp -rf ${HOME}/RPM/log/*prunner*.log RPM/log/
    - mkdir -p korinf-log; cp -rf ${HOME}/RPM/tmp/korinf-log/* korinf-log/

  artifacts:
    paths:
    - RPM/log
    - korinf-log
    expire_in: 10 days

  only:
    - master

  tags:
    - rx-build
